# Generated by Django 3.1.7 on 2021-02-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brend',
            new_name='brand',
        ),
    ]
