# Generated by Django 3.1.7 on 2021-03-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210226_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description1',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание товара 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание товара 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='description3',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание товара 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='description4',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание товара 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='description5',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание товара 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='description6',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание товара 6'),
        ),
        migrations.AddField(
            model_name='product',
            name='description7',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание товара 7'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена товара'),
        ),
    ]
